src/Entity/Country.php
<?php

namespace App\Entity;

use App\Repository\CountryRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CountryRepository::class)]
class Country
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?int $code = null;

    #[ORM\Column(length: 2)]
    private ?string $alpha2 = null;

    #[ORM\Column(length: 3)]
    private ?string $alpha3 = null;

    #[ORM\Column(length: 45)]
    private ?string $name_english = null;

    #[ORM\Column(length: 45)]
    private ?string $name_french = null;

    #[ORM\OneToMany(mappedBy: 'country', targetEntity: Movie::class)]
    private Collection $movies;

    public function __construct()
    {
        $this->movies = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCode(): ?int
    {
        return $this->code;
    }

    public function setCode(int $code): self
    {
        $this->code = $code;

        return $this;
    }

    public function getAlpha2(): ?string
    {
        return $this->alpha2;
    }

    public function setAlpha2(string $alpha2): self
    {
        $this->alpha2 = $alpha2;

        return $this;
    }

    public function getAlpha3(): ?string
    {
        return $this->alpha3;
    }

    public function setAlpha3(string $alpha3): self
    {
        $this->alpha3 = $alpha3;

        return $this;
    }

    public function getNameEnglish(): ?string
    {
        return $this->name_english;
    }

    public function setNameEnglish(string $name_english): self
    {
        $this->name_english = $name_english;

        return $this;
    }

    public function getNameFrench(): ?string
    {
        return $this->name_french;
    }

    public function setNameFrench(string $name_french): self
    {
        $this->name_french = $name_french;

        return $this;
    }

    /**
     * @return Collection<int, Movie>
     */
    public function getMovies(): Collection
    {
        return $this->movies;
    }

    public function addMovie(Movie $movie): self
    {
        if (!$this->movies->contains($movie)) {
            $this->movies->add($movie);
            $movie->setCountry($this);
        }

        return $this;
    }

    public function removeMovie(Movie $movie): self
    {
        if ($this->movies->removeElement($movie)) {
            // set the owning side to null (unless already changed)
            if ($movie->getCountry() === $this) {
                $movie->setCountry(null);
            }
        }

        return $this;
    }
}

src/Entity/Movie.php
<?php

namespace App\Entity;

use App\Repository\MovieRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: MovieRepository::class)]
class Movie
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[Assert\NotNull(message: "Renseigne un titre pour le film !")]
    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[Assert\Range(
        notInRangeMessage: "Le premier film est sorti en 1895 et nous sommes en 2023. Choisis une date dans cet intervalle :)",
        min: 1895, max: 2023
    )]
    #[ORM\Column(nullable: true)]
    private ?int $releaseYear = null;

    #[ORM\Column(nullable: true)]
    private ?bool $wasSeen = null;

    #[ORM\ManyToOne(inversedBy: 'movies')]
    private ?Country $country = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getReleaseYear(): ?int
    {
        return $this->releaseYear;
    }

    public function setReleaseYear(?int $releaseYear): self
    {
        $this->releaseYear = $releaseYear;

        return $this;
    }

    public function isWasSeen(): ?bool
    {
        return $this->wasSeen;
    }

    public function setWasSeen(?bool $wasSeen): self
    {
        $this->wasSeen = $wasSeen;

        return $this;
    }

    public function getCountry(): ?Country
    {
        return $this->country;
    }

    public function setCountry(?Country $country): self
    {
        $this->country = $country;

        return $this;
    }
}

src/Controller/MovieController.php
<?php

namespace App\Controller;

use App\Entity\Movie;
use App\Form\MovieFormType;
use App\Repository\MovieRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/movie', name: 'movie')]
class MovieController extends AbstractController
{
    #[Route('/create', name: '_create')]
    public function create(
        Request $request,
        EntityManagerInterface $entityManager
    ): Response
    {
        $movie = new Movie();
        $movieForm = $this->createForm(MovieFormType::class, $movie);
        $movieForm->handleRequest($request);
        if ($movieForm->isSubmitted() && $movieForm->isValid()) {
            $entityManager->persist($movie);
            $entityManager->flush();
            $this->addFlash('success', 'Film ajouté à la liste !');
            return $this->redirectToRoute('movie_list');
        }
        return $this->render('movie/create.html.twig',
            compact('movieForm')
        );
    }

    #[Route('/', name: '_list')]
    public function list(
        MovieRepository $movieRepository
    ): Response
    {
        $movies = $movieRepository->findAll();
        return $this->render('movie/list.html.twig',
            compact('movies')
        );
    }

    #[Route('/{id}', name: '_detail')]
    public function detail(
        Movie $id,
        MovieRepository $movieRepository
    ): Response
    {
        $movie = $movieRepository->find($id);
        return $this->render('movie/detail.html.twig',[
            'movie' => $id
        ]);
    }
}

templates/movie/create.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h2>Ajouter un film à la liste</h2>
    {{ form_start(movieForm) }}
    {{ form_widget(movieForm) }}
    <button>OK</button>
    {{ form_end(movieForm) }}
    <br><hr>
    <p><a href="{{ path('movie_list') }}" class="bt">Retour à la liste de films</a></p>
    <p><a href="{{ path('home_index') }}" class="bt">Retour à l'accueil</a></p>
{% endblock %}

{% block title %}{{ parent() }} - Ajout d'un film{% endblock %}

templates/movie/detail.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div>
        Le film n°{{ movie.id }} est <strong>{{ movie.title }}</strong> ({{ movie.country.nameFrench }}) sorti en {{ movie.releaseYear }}.<br><br>
        {% if movie.wasSeen %}
            Vu !!
        {% else %}
            Pas encore vu  !
        {% endif %}
    </div>
    <br><hr>
    <p><a href="{{ path('movie_list') }}" class="bt">Retour à la liste de films</a></p>
    <p><a href="{{ path('home_index') }}" class="bt">Retour à l'accueil</a></p>
{% endblock %}

{% block title %}{{ parent() }} - Détails d'un film{% endblock %}

templates/movie/list.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h2>Liste de films à voir absolument</h2>
    <ol>
        {% for movie in movies %}
            <li><a href="{{ path('movie_detail', {'id': movie.id}) }}">{{ movie.title }}</a> ({{ movie.country.nameFrench }}) sorti en {{ movie.releaseYear }}</li>
        {% else %}
            Aucun film n'a été ajouté pour l'instant.
        {% endfor %}
    </ol><br>
    <h3><a href="{{ path('movie_create') }}" class="bt">Ajouter un film</a></h3>
    <br><hr>
    <p><a href="{{ path('home_index') }}" class="bt">Retour à l'accueil</a></p>
{% endblock %}

{% block title %}{{ parent() }} - Liste de films{% endblock %}